[package]
name = "zkp-auth-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.14.0"
bcrypt = "0.15.0" 
bls12_381 = "0.8.0"
sha2 = "0.10.8" 
rand = "0.8.5" 
pairing = "0.23.0" 